/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface ScButtonDecorator {
    }
    interface ScInputDecorator {
    }
    interface ScPDecorator {
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLScButtonDecoratorElement extends Components.ScButtonDecorator, HTMLStencilElement {
    }
    var HTMLScButtonDecoratorElement: {
        prototype: HTMLScButtonDecoratorElement;
        new (): HTMLScButtonDecoratorElement;
    };
    interface HTMLScInputDecoratorElement extends Components.ScInputDecorator, HTMLStencilElement {
    }
    var HTMLScInputDecoratorElement: {
        prototype: HTMLScInputDecoratorElement;
        new (): HTMLScInputDecoratorElement;
    };
    interface HTMLScPDecoratorElement extends Components.ScPDecorator, HTMLStencilElement {
    }
    var HTMLScPDecoratorElement: {
        prototype: HTMLScPDecoratorElement;
        new (): HTMLScPDecoratorElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "sc-button-decorator": HTMLScButtonDecoratorElement;
        "sc-input-decorator": HTMLScInputDecoratorElement;
        "sc-p-decorator": HTMLScPDecoratorElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface ScButtonDecorator {
    }
    interface ScInputDecorator {
    }
    interface ScPDecorator {
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "sc-button-decorator": ScButtonDecorator;
        "sc-input-decorator": ScInputDecorator;
        "sc-p-decorator": ScPDecorator;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "sc-button-decorator": LocalJSX.ScButtonDecorator & JSXBase.HTMLAttributes<HTMLScButtonDecoratorElement>;
            "sc-input-decorator": LocalJSX.ScInputDecorator & JSXBase.HTMLAttributes<HTMLScInputDecoratorElement>;
            "sc-p-decorator": LocalJSX.ScPDecorator & JSXBase.HTMLAttributes<HTMLScPDecoratorElement>;
        }
    }
}
